-- Fatia "Categorias de serviço": tabela `categorias_servico` + coluna
-- `servicos.categoria_id`.
--
-- Rode este arquivo UMA vez no SQL Editor do Supabase (projeto de staging),
-- DEPOIS de `servicos`/`estabelecimentos` existirem. IDs são inteiros (bigint
-- identity) pra casar com `servicos`/`estabelecimentos`.
--
-- >>> IMPORTANTE (RLS): a policy abaixo assume a MESMA lógica das policies de
--     `servicos`/`profissionais` — perfil do usuário (`perfis.user_id =
--     auth.uid()`) manda; papel 'global' gerencia todos os salões, os demais
--     ficam presos ao próprio `estabelecimento_id`. Confira contra as suas
--     policies reais e ajuste o predicado se necessário.

-- ---------------------------------------------------------------------------
-- Tabela: categorias_servico
--   Agrupa os serviços de um salão (ex.: "Cabelo", "Barba"). `ordem` define a
--   sequência de exibição; a UI reordena trocando `ordem` entre vizinhos.
-- ---------------------------------------------------------------------------
create table if not exists public.categorias_servico (
  id                 bigint generated by default as identity primary key,
  estabelecimento_id bigint not null references public.estabelecimentos (id) on delete cascade,
  nome               text   not null,
  ordem              integer not null default 0
);

create index if not exists categorias_servico_estabelecimento_idx
  on public.categorias_servico (estabelecimento_id);

-- ---------------------------------------------------------------------------
-- Coluna: servicos.categoria_id
--   Opcional (null = "Sem categoria"). ON DELETE SET NULL: apagar a categoria
--   apenas desagrupa os serviços, sem removê-los.
-- ---------------------------------------------------------------------------
alter table public.servicos
  add column if not exists categoria_id bigint
    references public.categorias_servico (id) on delete set null;

create index if not exists servicos_categoria_idx
  on public.servicos (categoria_id);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.categorias_servico enable row level security;

-- O usuário gerencia as categorias do estabelecimento do seu perfil; 'global'
-- gerencia todas.
create policy "categorias_servico_admin_all"
  on public.categorias_servico
  for all
  to authenticated
  using (
    exists (
      select 1 from public.perfis pf
      where pf.user_id = auth.uid()
        and (pf.papel = 'global' or pf.estabelecimento_id = categorias_servico.estabelecimento_id)
    )
  )
  with check (
    exists (
      select 1 from public.perfis pf
      where pf.user_id = auth.uid()
        and (pf.papel = 'global' or pf.estabelecimento_id = categorias_servico.estabelecimento_id)
    )
  );
