-- Registro de cada brinde de fidelidade concedido (botão "Marcar brinde
-- concedido" no card `fidelidade_disponivel` da aba Pendentes do /admin —
-- ver TIPOS_PENDENCIA em app/[salon]/admin/page.js). Não guarda QUAL brinde
-- nem quantidade: é só o carimbo que zera a contagem da cliente pra próxima
-- fidelidade (ver verificarFidelidadeClientes em lib/fidelidade.js, que conta
-- os atendimentos concluídos desde o `criado_em` mais recente aqui).
--
-- Rode este arquivo no SQL Editor do Supabase (projeto de staging).

create table if not exists public.fidelidade_resgates (
  id                 bigint generated by default as identity primary key,
  cliente_id         bigint  not null references public.clientes (id) on delete cascade,
  estabelecimento_id bigint  not null references public.estabelecimentos (id) on delete cascade,
  criado_em          timestamptz not null default now()
);

create index if not exists fidelidade_resgates_cliente_idx
  on public.fidelidade_resgates (estabelecimento_id, cliente_id, criado_em desc);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.fidelidade_resgates enable row level security;

-- Mesma lógica das demais tabelas do admin (ver pendencias_admin): perfil do
-- usuário manda; 'global' gerencia todos os salões, os demais ficam presos ao
-- próprio estabelecimento_id. Só o /admin autenticado lê/grava resgates — sem
-- acesso anônimo (diferente de `clientes`/`agendamentos`).
create policy "fidelidade_resgates_admin_all"
  on public.fidelidade_resgates
  for all
  to authenticated
  using (
    exists (
      select 1 from public.perfis pf
      where pf.user_id = auth.uid()
        and (pf.papel = 'global' or pf.estabelecimento_id = fidelidade_resgates.estabelecimento_id)
    )
  )
  with check (
    exists (
      select 1 from public.perfis pf
      where pf.user_id = auth.uid()
        and (pf.papel = 'global' or pf.estabelecimento_id = fidelidade_resgates.estabelecimento_id)
    )
  );
