-- Importação em massa do Google Calendar pro reserva-horario (ver
-- app/api/google-calendar/importar/route.js e
-- components/ModalImportarGoogleCalendar.js).
--
-- google_calendar_id_importacao – qual calendário da conta conectada (ver
--   estabelecimentos_google_calendar.sql) é o de atendimento real, escolhido
--   pela dona num dropdown alimentado por calendarList.list() — evita
--   importar o calendário de feriados/pessoal junto. Editado direto pelo
--   /admin autenticado (mesma policy de UPDATE de
--   estabelecimentos_update_policy.sql), null enquanto não escolhido.
--
-- calendar_import_ignorados – candidatos que a dona desmarcou na tela de
--   revisão da importação, pra não voltar a aparecer nas próximas buscas de
--   candidatos. Só o service role (rota server-side) lê/grava essa tabela —
--   RLS habilitada sem nenhuma policy, mesmo padrão de restrição de
--   google_calendar_tokens.
--
-- Já aplicado no projeto de staging; arquivo aqui só documenta o schema
-- (mesma convenção das demais migrations em sql/).

alter table public.estabelecimentos
  add column if not exists google_calendar_id_importacao text;

create table if not exists public.calendar_import_ignorados (
  id                 bigint generated by default as identity primary key,
  estabelecimento_id bigint not null references public.estabelecimentos (id) on delete cascade,
  google_event_id    text   not null,
  criado_em          timestamptz not null default now(),
  unique (estabelecimento_id, google_event_id)
);

alter table public.calendar_import_ignorados enable row level security;
