-- Tabela `pendencias_admin`: itens que a dona precisa ver/agir na aba
-- "Pendentes" do /admin além dos agendamentos com status = 'pendente' (ex.:
-- cancelamento feito pela cliente no painel público, ver
-- components/PainelCliente.js). Inserida pelo webhook de notificações
-- (app/api/notificacoes) usando o service role, então RLS não bloqueia o
-- insert; as policies abaixo só cobrem o SELECT/UPDATE feitos pelo /admin
-- autenticado (ler a lista e marcar `resolvido` ao arquivar).
--
-- `tipo` decide o conjunto de botões/ações do card (ver TIPOS_PENDENCIA em
-- app/[salon]/admin/page.js) — hoje só 'cancelamento_cliente', mas a coluna é
-- texto livre pra caber tipos novos sem migration.
-- `agendamento_id` é opcional (nem toda pendência futura precisa estar presa
-- a um agendamento) e some sozinho (SET NULL) se o agendamento for apagado,
-- sem apagar a pendência.
--
-- Rode este arquivo no SQL Editor do Supabase (projeto de staging).

create table if not exists public.pendencias_admin (
  id                 bigint generated by default as identity primary key,
  estabelecimento_id bigint  not null references public.estabelecimentos (id) on delete cascade,
  tipo               text    not null,
  titulo             text    not null,
  descricao          text,
  agendamento_id     bigint  references public.agendamentos (id) on delete set null,
  resolvido          boolean not null default false,
  created_at         timestamptz not null default now()
);

create index if not exists pendencias_admin_estabelecimento_idx
  on public.pendencias_admin (estabelecimento_id, resolvido);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.pendencias_admin enable row level security;

-- Mesma lógica das demais tabelas do admin (ver categorias_servico/
-- profissionais): perfil do usuário manda; 'global' gerencia todos os salões,
-- os demais ficam presos ao próprio estabelecimento_id.
create policy "pendencias_admin_admin_all"
  on public.pendencias_admin
  for all
  to authenticated
  using (
    exists (
      select 1 from public.perfis pf
      where pf.user_id = auth.uid()
        and (pf.papel = 'global' or pf.estabelecimento_id = pendencias_admin.estabelecimento_id)
    )
  )
  with check (
    exists (
      select 1 from public.perfis pf
      where pf.user_id = auth.uid()
        and (pf.papel = 'global' or pf.estabelecimento_id = pendencias_admin.estabelecimento_id)
    )
  );
