-- Fatia "Profissionais": tabelas `profissionais` e `horarios_trabalho`.
--
-- Rode este arquivo UMA vez no SQL Editor do Supabase (projeto de staging).
-- IDs são inteiros (bigint identity) pra casar com `estabelecimentos`/`servicos`,
-- que usam ids 1, 2, 3...
--
-- >>> IMPORTANTE (RLS): as policies abaixo assumem a MESMA lógica das policies de
--     `servicos` — perfil do usuário (`perfis.user_id = auth.uid()`) manda; papel
--     'global' gerencia todos os salões, os demais ficam presos ao próprio
--     `estabelecimento_id`. Confira contra as suas policies reais de `servicos` e
--     ajuste o predicado se necessário.

-- ---------------------------------------------------------------------------
-- Tabela: profissionais
-- ---------------------------------------------------------------------------
create table if not exists public.profissionais (
  id                 bigint generated by default as identity primary key,
  estabelecimento_id bigint  not null references public.estabelecimentos (id) on delete cascade,
  nome               text    not null,
  ativo              boolean not null default true,   -- "excluir" é soft delete (ativo=false)
  created_at         timestamptz not null default now()
);

create index if not exists profissionais_estabelecimento_idx
  on public.profissionais (estabelecimento_id);

-- ---------------------------------------------------------------------------
-- Tabela: horarios_trabalho
--   Uma linha por (profissional_id, dia_semana). dia_semana: 0=domingo … 6=sábado.
-- ---------------------------------------------------------------------------
create table if not exists public.horarios_trabalho (
  id             bigint generated by default as identity primary key,
  profissional_id bigint   not null references public.profissionais (id) on delete cascade,
  dia_semana     smallint  not null check (dia_semana between 0 and 6),
  hora_inicio    time      not null,
  hora_fim       time      not null,
  almoco_inicio  time,
  almoco_fim     time,

  -- só uma linha por (profissional, dia)
  constraint horarios_trabalho_prof_dia_uk unique (profissional_id, dia_semana),

  -- fim do expediente depois do início
  constraint horarios_trabalho_janela_chk check (hora_fim > hora_inicio),

  -- almoço é tudo-ou-nada (ou preenche início e fim, ou deixa ambos vazios)
  constraint horarios_trabalho_almoco_par_chk check (
    (almoco_inicio is null and almoco_fim is null)
    or (almoco_inicio is not null and almoco_fim is not null)
  )
);

create index if not exists horarios_trabalho_profissional_idx
  on public.horarios_trabalho (profissional_id);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.profissionais    enable row level security;
alter table public.horarios_trabalho enable row level security;

-- profissionais: o usuário gerencia os do estabelecimento do seu perfil; 'global'
-- gerencia todos.
create policy "profissionais_admin_all"
  on public.profissionais
  for all
  to authenticated
  using (
    exists (
      select 1 from public.perfis pf
      where pf.user_id = auth.uid()
        and (pf.papel = 'global' or pf.estabelecimento_id = profissionais.estabelecimento_id)
    )
  )
  with check (
    exists (
      select 1 from public.perfis pf
      where pf.user_id = auth.uid()
        and (pf.papel = 'global' or pf.estabelecimento_id = profissionais.estabelecimento_id)
    )
  );

-- horarios_trabalho: herda o acesso pelo estabelecimento do profissional dono da
-- linha.
create policy "horarios_trabalho_admin_all"
  on public.horarios_trabalho
  for all
  to authenticated
  using (
    exists (
      select 1
      from public.profissionais pr
      join public.perfis pf on pf.user_id = auth.uid()
      where pr.id = horarios_trabalho.profissional_id
        and (pf.papel = 'global' or pf.estabelecimento_id = pr.estabelecimento_id)
    )
  )
  with check (
    exists (
      select 1
      from public.profissionais pr
      join public.perfis pf on pf.user_id = auth.uid()
      where pr.id = horarios_trabalho.profissional_id
        and (pf.papel = 'global' or pf.estabelecimento_id = pr.estabelecimento_id)
    )
  );
