-- Regras ESPECIAIS de sinal: valor e cobrança por SERVIÇO e/ou por PERÍODO de
-- datas, por cima do padrão do salão (`estabelecimentos.sinal_regra` +
-- `sinal_valor_centavos`).
--
-- O que passa a caber: "em dezembro todo mundo paga sinal", "a progressiva
-- sempre pede R$ 100", "nesta semana de curso ninguém paga". Até aqui a
-- cobrança era um escalar só por salão e nada disso tinha onde morar.
--
-- Rode este arquivo no SQL Editor do Supabase (projeto de STAGING primeiro).
-- É IDEMPOTENTE: `create table if not exists`, `create or replace function`,
-- `drop policy if exists` antes de cada `create policy`. Rodar duas vezes não
-- muda nada.
--
-- >>> IMPORTANTE (RLS): as policies abaixo assumem a MESMA lógica das policies
--     de `servicos`/`categorias_servico` — perfil do usuário
--     (`perfis.user_id = auth.uid()`) manda; papel 'global' gerencia todos os
--     salões, os demais ficam presos ao próprio `estabelecimento_id`. Confira
--     contra as suas policies reais antes de aplicar.
--
-- >>> A LEITURA É PÚBLICA, de propósito. O /agendar decide no NAVEGADOR se
--     cobra sinal e quanto (ver precisaSinal em
--     components/FormularioAgendamento.js), então o anônimo precisa enxergar
--     as regras do salão. O que fica exposto é a tabela de preços do sinal —
--     a mesma informação que a cliente vê na tela do Pix segundos depois.
--     Nenhum dado de cliente, agendamento ou credencial passa por aqui.
--     Mesmo grau de exposição de `servicos`, que também é lida por anon.

-- ---------------------------------------------------------------------------
-- 1. Tabela
-- ---------------------------------------------------------------------------
-- UMA regra que cobre N serviços vira N LINHAS com o mesmo `grupo_id` — mesmo
-- padrão de `ausencias.grupo_id` (ver "Datas avulsas" em
-- app/[salon]/admin/GerenciarProfissionais.js). A UI cadastra e exclui pelo
-- grupo; o resolver trabalha linha a linha, sem nunca precisar saber que o
-- grupo existe.
--
-- Colunas nuláveis e o que cada nulo SIGNIFICA (nenhum deles é "não sei"):
--   servico_id  null -> todos os serviços do salão
--   data_*      null -> sempre (regra sem período)
--   valor_centavos null -> usa `estabelecimentos.sinal_valor_centavos`
--
-- `on delete cascade` no serviço: uma regra sobre um serviço que não existe
-- mais não tem o que decidir. Na prática o /admin quase nunca apaga serviço de
-- verdade (usa ativo=false + oculto=true quando há agendamentos vinculados —
-- ver sql/servicos_oculto.sql), então o cascade é a borda, não o caminho.
create table if not exists public.sinal_regras_especiais (
  id                 bigint generated by default as identity primary key,
  estabelecimento_id bigint not null references public.estabelecimentos (id) on delete cascade,
  grupo_id           uuid   not null,
  servico_id         bigint references public.servicos (id) on delete cascade,
  data_inicio        date,
  data_fim           date,
  cobranca           text   not null,
  valor_centavos     integer,
  criado_em          timestamptz not null default now()
);

-- Constraints em ALTER separado (e não inline no create) pra que o arquivo
-- continue idempotente num banco onde a tabela já existe: `create table if not
-- exists` não acrescenta constraint nenhuma numa tabela que já está lá.
alter table public.sinal_regras_especiais
  drop constraint if exists sinal_regras_especiais_cobranca_check;

alter table public.sinal_regras_especiais
  add constraint sinal_regras_especiais_cobranca_check
  check (cobranca in ('todas', 'exceto_manutencao', 'nao_cobrar'));

-- As duas datas andam JUNTAS: período pela metade ("de dezembro em diante")
-- não existe nesta feature, e permitir um nulo solto faria o resolver ter que
-- inventar a outra ponta. `data_fim >= data_inicio` fecha o intervalo
-- invertido, que passaria silenciosamente como "regra que nunca vale".
alter table public.sinal_regras_especiais
  drop constraint if exists sinal_regras_especiais_periodo_check;

alter table public.sinal_regras_especiais
  add constraint sinal_regras_especiais_periodo_check
  check (
    (data_inicio is null and data_fim is null)
    or (data_inicio is not null and data_fim is not null and data_fim >= data_inicio)
  );

create index if not exists sinal_regras_especiais_estabelecimento_idx
  on public.sinal_regras_especiais (estabelecimento_id);

create index if not exists sinal_regras_especiais_grupo_idx
  on public.sinal_regras_especiais (grupo_id);

create index if not exists sinal_regras_especiais_servico_idx
  on public.sinal_regras_especiais (servico_id);

-- ---------------------------------------------------------------------------
-- 2. RLS
-- ---------------------------------------------------------------------------
alter table public.sinal_regras_especiais enable row level security;

-- A dona gerencia as regras do estabelecimento do seu perfil; 'global'
-- gerencia todos. Espelha `categorias_servico_admin_all`.
drop policy if exists "sinal_regras_especiais_admin_all" on public.sinal_regras_especiais;

create policy "sinal_regras_especiais_admin_all"
  on public.sinal_regras_especiais
  for all
  to authenticated
  using (
    exists (
      select 1 from public.perfis pf
      where pf.user_id = auth.uid()
        and (pf.papel = 'global' or pf.estabelecimento_id = sinal_regras_especiais.estabelecimento_id)
    )
  )
  with check (
    exists (
      select 1 from public.perfis pf
      where pf.user_id = auth.uid()
        and (pf.papel = 'global' or pf.estabelecimento_id = sinal_regras_especiais.estabelecimento_id)
    )
  );

-- Leitura pública (ver o cabeçalho). `authenticated` entra junto porque a
-- mesma página pública roda logada quando a dona abre o próprio link com a
-- sessão do /admin aberta — a policy de admin acima cobre só o estabelecimento
-- dela, e sem esta a tela pública de OUTRO salão ficaria sem regras.
drop policy if exists "sinal_regras_especiais_public_select" on public.sinal_regras_especiais;

create policy "sinal_regras_especiais_public_select"
  on public.sinal_regras_especiais
  for select
  to anon, authenticated
  using (
    exists (
      select 1 from public.estabelecimentos e
      where e.id = sinal_regras_especiais.estabelecimento_id
        and e.ativo = true
    )
  );

-- ---------------------------------------------------------------------------
-- 3. sinal_resolver — o VALOR do sinal de um agendamento
-- ---------------------------------------------------------------------------
-- Espelho em SQL de `resolverSinal` (lib/sinalRegra.js). Duplicação
-- CONSCIENTE, pelo mesmo motivo da antecedência mínima: o valor gravado não
-- pode depender do que o navegador manda (ver o comentário de
-- agendamento_declarar_sinal), e a tela precisa mostrar o número antes de
-- gravar. Mexeu num lado, mexa no outro.
--
-- DEVOLVE SÓ O VALOR, e não o par { cobra, valor } do módulo JS. `cobra`
-- depende de `ehNovo` e `naListaBloqueio`, que são fatos sobre a CLIENTE e não
-- estão na linha do agendamento — e, mais importante, não há consumidor: quem
-- chama esta função é a RPC de declarar sinal, que só roda sobre uma linha já
-- em 'aguardando_sinal'. A cobrança já foi decidida lá atrás, no wizard. Fazer
-- a função responder "cobra?" exigiria recontar o histórico da cliente e
-- reabrir a etiqueta dela pra responder uma pergunta que ninguém faz.
--
-- Por que o COALESCE de dois níveis basta pra cobrir os passos 3 e 4 do
-- resolver: os dois casos em que o valor cai pro padrão do salão — "nenhuma
-- regra venceu" e "a regra vencedora tem valor_centavos nulo" — produzem NULL
-- na subconsulta, e o fallback é o mesmo nos dois. Não é atalho, é a mesma
-- conta escrita uma vez só.
--
-- `order by` reproduz a especificidade do JS (serviço pesa 2, período pesa 1),
-- com `criado_em desc` como desempate — rede de segurança, já que a UI barra
-- sobreposição no cadastro.
--
-- STABLE e não IMMUTABLE: lê tabela.
create or replace function public.sinal_resolver(p_agendamento_id uuid)
returns integer
language sql
stable
security definer
set search_path = public, pg_temp
as $fn$
  select coalesce(
    (
      select r.valor_centavos
        from public.agendamentos a
        join public.sinal_regras_especiais r
          on r.estabelecimento_id = a.estabelecimento_id
       where a.id = p_agendamento_id
         and (r.servico_id is null or r.servico_id = a.servico_id)
         and (
           r.data_inicio is null
           or (a.data >= r.data_inicio and a.data <= r.data_fim)
         )
       order by (case when r.servico_id is not null then 2 else 0 end)
              + (case when r.data_inicio is not null then 1 else 0 end) desc,
                r.criado_em desc
       limit 1
    ),
    (
      select e.sinal_valor_centavos
        from public.agendamentos a
        join public.estabelecimentos e on e.id = a.estabelecimento_id
       where a.id = p_agendamento_id
    )
  );
$fn$;

-- ---------------------------------------------------------------------------
-- 4. agendamento_declarar_sinal — nova versão
-- ---------------------------------------------------------------------------
-- ÚNICA mudança em relação a sql/rpcs_agendamento_publico.sql: o valor gravado
-- deixa de ser `e.sinal_valor_centavos` cru e passa a sair de
-- `sinal_resolver`. Com `sinal_regras_especiais` vazia os dois são o MESMO
-- número, por construção (ver o COALESCE acima) — é por isso que este arquivo
-- pode ser aplicado antes de existir uma única regra cadastrada.
--
-- O `coalesce(sinal_valor_centavos, ...)` do UPDATE fica INTACTO: linha que já
-- tem valor (cobrança AbacatePay criada em gerar-cobranca, ou herança da
-- remarcação) mantém o que foi realmente cobrado, e agora isso vale também
-- contra uma regra especial cadastrada DEPOIS do pagamento.
--
-- Todo o resto — idempotência, a guarda de status, o `for update of a`, o
-- `pendente_desde` só quando nulo — é cópia literal da versão anterior. Se
-- aquele arquivo mudar, esta cópia precisa acompanhar; a versão que vale é a
-- que foi aplicada por último no banco.
create or replace function public.agendamento_declarar_sinal(p_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_status                text;
  v_sinal_declarado       boolean;
  v_sinal_estabelecimento integer;
begin
  select a.status, a.sinal_declarado_pago
    into v_status, v_sinal_declarado
    from public.agendamentos a
    join public.estabelecimentos e on e.id = a.estabelecimento_id
   where a.id = p_id
     and e.ativo = true
     for update of a;

  if v_status is null then
    return false;
  end if;

  -- DEPOIS do lock, e não no mesmo SELECT: o resolver lê `agendamentos` de
  -- novo por dentro, e misturar isso com o `for update of a` é pedir pro
  -- planner resolver uma pergunta que não precisa existir. A linha já está
  -- travada aqui, então o valor sai do mesmo estado consistente.
  v_sinal_estabelecimento := public.sinal_resolver(p_id);

  -- Já declarado: sucesso sem gravar nada (ver IDEMPOTÊNCIA no arquivo
  -- original).
  if v_status = 'pendente' and v_sinal_declarado is true then
    return true;
  end if;

  -- Fora isso, só sai de 'aguardando_sinal'. Um 'confirmado' não volta pra
  -- 'pendente' por gesto da cliente, e um 'cancelado' não ressuscita.
  if v_status <> 'aguardando_sinal' then
    return false;
  end if;

  update public.agendamentos
     set status               = 'pendente',
         sinal_declarado_pago = true,
         pendente_desde       = coalesce(pendente_desde, now()),
         sinal_valor_centavos = coalesce(sinal_valor_centavos, v_sinal_estabelecimento)
   where id = p_id;

  return true;
end;
$fn$;

-- ---------------------------------------------------------------------------
-- 5. Permissões
-- ---------------------------------------------------------------------------
-- REVOKE de PUBLIC antes do GRANT: toda função nasce com EXECUTE pra PUBLIC.
--
-- `sinal_resolver` NÃO é concedida a anon/authenticated: o único caminho que a
-- executa é de dentro de `agendamento_declarar_sinal`, que é SECURITY DEFINER
-- e portanto roda como o dono. Conceder EXECUTE daria ao anônimo um oráculo
-- de valor por id de agendamento sem nenhum ganho — o navegador já resolve o
-- mesmo número localmente, com as regras que a policy de leitura entrega.
revoke execute on function public.sinal_resolver(uuid) from public;

-- Recriada acima com `create or replace`: o replace PRESERVA os grants
-- existentes, então esta linha é redundante num banco que já aplicou
-- sql/rpcs_agendamento_publico.sql. Fica pro caso deste arquivo rodar antes
-- daquele (ordem invertida num tenant novo).
revoke execute on function public.agendamento_declarar_sinal(uuid) from public;
grant execute on function public.agendamento_declarar_sinal(uuid) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- ROLLBACK
-- ---------------------------------------------------------------------------
-- Voltar ao comportamento anterior é recriar `agendamento_declarar_sinal` a
-- partir de sql/rpcs_agendamento_publico.sql (a versão com
-- `e.sinal_valor_centavos`) — faça ISSO PRIMEIRO, senão o drop da função
-- abaixo falha por dependência.
--
-- drop function if exists public.sinal_resolver(uuid);
-- drop table if exists public.sinal_regras_especiais;
